# Generated by Django 2.0.4 on 2018-04-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='flag',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
