# Generated by Django 2.0.4 on 2018-04-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_challenge_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenge',
            old_name='dicovered_by',
            new_name='discovered_by',
        ),
    ]
